### ISSUE TITLE
[Feature Request] Plymouth integration

### ISSUE THREAD

**Issue by 6XGate** [eworm-de/pacman-offline#2]
It would be great if this could have some integration with Plymouth's offline update mode. The only issue with something that seems to work really great; is when using Plymouth, there is no indication that an update is in progress or why the system is taking so long to boot. (reboot in this case)

**Comment by eworm-de** [comment]
Never used Plymouth... Any idea what is required?

**Comment by 6XGate** [comment]
Looks like it's just a few command line calls to Plymouth if it's installed. You can always copy [Manjaro's homework](https://gitlab.manjaro.org/applications/pamac-cli/-/blob/main/data/offline-upgrade/pamac-offline-upgrade.service) :smile:

**Comment by eworm-de** [comment]
Well, I call a single script from systemd service file. Even if I put the `plymouth` commands into the script... About 99% of the time is used by `pacman`, and I can not give details progress.

Anyway... Does this change to the service file improve the situation?
```
diff --git a/systemd/pacman-offline.service b/systemd/pacman-offline.service
index 01ce462..bd8ee49 100644
--- a/systemd/pacman-offline.service
+++ b/systemd/pacman-offline.service
@@ -11,4 +11,6 @@ OnFailure=reboot.target
 Type=oneshot
 StandardOutput=tty
 StandardError=tty
+ExecStartPre=-/usr/bin/plymouth change-mode --updates
+ExecStartPre=-/usr/bin/plymouth system-update --progress=20
 ExecStart=/usr/lib/systemd/scripts/pacman-offline
```

**Comment by 6XGate** [comment]
that seems to work fine... better than Manjaro's which did a post command like they meant pre :smile:
