### ISSUE TITLE
[Feature Request] Improvements to readme

### ISSUE THREAD

**Issue by 6XGate** [eworm-de/pacman-offline#3]
It would be great if there was some examples of how to use this. It took a bit of guess work to figure this out. I recommend examples of:

- Actually preparing an offline update (just the `-y` flag I'm guessing)
- Rebooting immediately (guessing `-yr`)
- And maybe some example of integrating with the `gnome-shell-extension-arch-update` package (from AUR). I set its update command to `pkexec pacman-offline -fcyr` personally.

**Comment by eworm-de** [comment]
Yes, the documentation is lacking some details... 🤪 Essentially all. 😜

I will try to find some time to fill the gap.

**Comment by eworm-de** [comment]
Also add some info about the timers in 5c7096fc4abe8d513157ea552d6b807e2b0084b7.
